---
name: 'double_integrator_test_rss_double_integrator/best_model'

# Environment
env: 'double_integrator'
obstacle_type: 'narrow_passages'
world_dim: 2
state_dim: 4
control_dim: 2
goal_dim: 4
dt: 0.01

# Model architecture
z_env_dim: 64
context_dim: 64
num_flows: 10
horizon: 40
flow_type: 'nvp'
vae_flow_prior: True
voxels: False

# randomization of parameters
device: 'cuda:0'
randomize_cost_params: False
# Only relevant if randomise_cost_params is True
condition_on_cost_params: False
param_dim: 0
min_sigma: 0.2
min_lengthscale: 0.02
min_vel_penalty: 0.01

num_envs: 100
episode_length: 100
normalize_costs: True

# controllers
sample_budget: 512
controllers:
  mppi:
    lambda: 0.9
    sigma: 1
    iters: 1
  icem:
    sigma: 0.75
    noise_param: 2.5
    elite_fraction: 0.1
    kept_elites: 0.3
    iters: 4
    momentum: 0.1
  flowmppi:
    lambda: 1
    sigma: 1
    iters: 1
    project: False
  flowmppi_project:
    lambda: 1
    sigma: 1
    iters: 1
    project: True
    M: 10
    learning_rate: 0.01
  flowicem:
    sigma: 0.75
    noise_param: 2.5
    elite_fraction: 0.25
    kept_elites: 0.25
    iters: 4
    momentum: 0.1
    project: False
  flowicem_project:
    sigma: 0.75
    noise_param: 2.5
    elite_fraction: 0.25
    kept_elites: 0.25
    iters: 4
    momentum: 0.1
    project: True
    M: 10
    learning_rate: 0.01



